# -*- coding: utf-8 -*-
"""Create copy of Bigquery tables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1chfKI64jxsTw-lNJsffB-540A8ykY4H8
"""

from google.colab import auth,drive
auth.authenticate_user()
from google.cloud import bigquery

drive.mount('/content/gdrive/')

dataset_name = "project_main"
project_id = "test-project"
client = bigquery.Client(project=project_id)

sql = """    
      SELECT *    
      FROM `project_id-dataset_name-table_name`
  """      
df = client.query(sql).to_dataframe() 
new_tbl = dataset_name+"."+"table_name"
pandas_gbq.to_gbq(df, new_tbl, project_id, if_exists="replace")
print("Table copied to ", new_tbl)